# Chapter 1: Tensors
Tensors are specialized data structures that are similar to arrays and matrices. In PyTorch, tensors encode the inputs and outputs of a model, as well as the model parameters. Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and ndarrays often share the same underlying memory, eleminating the need to copy data. Tensors are also optimized for automatic dfferentiation.

In [1]:
import torch
import numpy as np

## Initializing a Tensor:
Tensors can be initialized in a few ways:

### Directly from data:

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

### From a NumPy array:

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From other tensors:

In [4]:
x_ones = torch.ones_like(x_data)
print (f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print (f"Random Tensor: \n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.5785, 0.2482],
        [0.5302, 0.7312]])



### With random or constant values:

In [5]:
shape = (2,3,) # a tuple with dimensions for initializing tensors
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor_alt = torch.rand((2,3,), dtype=torch.float)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")
print(f"Random Tensor with coded dimensions: \n {rand_tensor_alt} ")

Random Tensor: 
 tensor([[0.8644, 0.7816, 0.9133],
        [0.1851, 0.5820, 0.6776]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Random Tensor with coded dimensions: 
 tensor([[0.2984, 0.7033, 0.9322],
        [0.4519, 0.9465, 0.1460]]) 


## Attributes of a Tensor:
Tensor attributes describe their shape, datatype, and the device they are located on.

In [6]:
tensor = torch.rand((3,4))

print (f"Shape of the tensor: {tensor.shape}.")
print (f"Data-type of the tensor: {tensor.dtype}.")
print (f"Device of the tensor: {tensor.device}")

Shape of the tensor: torch.Size([3, 4]).
Data-type of the tensor: torch.float32.
Device of the tensor: cpu


## Operations on a Tensor:
There are over 100 tensor opperations ranging from arithmatic, to linear algebra, to matrix manipulations, sampling and more. The PyTorch website provides a comprehensive list of available operations [here](https://pytorch.org/docs/stable/torch.html).

Each of the operations can be run on a GPU (typically faster than running on a CPU). By default, tensors are created on CPUs, and need to be explicitly moved to a GPU using the `.to` method. However, GPU memory being typically smaller than available memory, keep in mind that copying large tensors over may be computationally too expensive to process.

In [7]:
tensor = tensor.to('cuda' if torch.cuda.is_available() else 'cpu')

print (f"Shape of the tensor: {tensor.shape}.")
print (f"Data-type of the tensor: {tensor.dtype}.")
print (f"Device of the tensor: {tensor.device}")

Shape of the tensor: torch.Size([3, 4]).
Data-type of the tensor: torch.float32.
Device of the tensor: cuda:0


### Most standard NumPy operations are available:

### Indexing and slicing:


In [8]:
tensor = torch.ones(4,4)

print (f"First row: {tensor[0]}.")
print (f"First column: {tensor[:,0]}.")
print (f"Last column: {tensor[...,-1]}.")
tensor[:,1] = 0
print (tensor)

First row: tensor([1., 1., 1., 1.]).
First column: tensor([1., 1., 1., 1.]).
Last column: tensor([1., 1., 1., 1.]).
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors:
It is also possible to join two tensors with the `torch.cat` method along a given dimension. An alternative method to join tensors is the `torch.stack` method combining tensors along a **new** dimension.

In [9]:
tensor_1 = torch.ones((2,2))
tensor_2 = torch.zeros((2,2))
tensor_3 = torch.rand((2,2))

# torch.cat concatenates tensors along existing dimensions
tensor_cat_0 = torch.cat((tensor_1, tensor_2, tensor_3), dim = 0)
print (f"Shape of combined tensor (cat, dim=0): {tensor_cat_0.shape}")

# defining dimensions allows concatenation along different directions
tensor_cat_1 = torch.cat((tensor_1, tensor_2, tensor_3), dim = 1)
print (f"Shape of combined tensor (cat, dim=1): {tensor_cat_1.shape}")

# torch.stack concatenates tensors along a new dimension
tensor_stack_0 = torch.stack((tensor_1, tensor_2, tensor_3), dim = 0)
print (f"Shape of combined tensor (stack, dim = 0): {tensor_stack_0.shape}")

# defining dimensions stacks tensors along a different direction in the new tensor
tensor_stack_1 = torch.stack((tensor_1, tensor_2, tensor_3), dim = 1)
print (f"Shape of combined tensor (stack, dim = 1): {tensor_stack_1.shape}")

Shape of combined tensor (cat, dim=0): torch.Size([6, 2])
Shape of combined tensor (cat, dim=1): torch.Size([2, 6])
Shape of combined tensor (stack, dim = 0): torch.Size([3, 2, 2])
Shape of combined tensor (stack, dim = 1): torch.Size([2, 3, 2])


### Arithmatic operations:
Matrix multiplications can be done in several ways:

In [10]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)


y4 = torch.einsum('ij, kj-> ik', tensor, tensor)
print (y1)
print (y4)

assert torch.equal(y1,y2) and torch.equal(y2,y3) and torch.equal(y3,y4) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### Single-element tensors:
With a one-element tensor, like ones gotten from aggregating all values of a tensor, one can convert it into a Python numerical value using `item()`.

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print (agg_item, type(agg_item))

12.0 <class 'float'>


### In-place operations:
Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example `x.copy_(y)` or `x.t_()` makes changes to `x`.

In [12]:
print (f"Original tensor: \n{tensor}.\n")
tensor.add_(5)
print (f"Augmented tensor: \n{tensor}.\n")

Original tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]).

Augmented tensor: 
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]).



## Bridge with NumPy:
Tensors on the **CPU** and NumPy arrays share their underlying memory locations, and changing one will change the other:

In [14]:
t = torch.ones(5)
print (f"t: \n{t}\n")
n = t.numpy()
print (f"n: \n{n}\n")

t: 
tensor([1., 1., 1., 1., 1.])

n: 
[1. 1. 1. 1. 1.]



In [15]:
t.add_(2)

print (f"t: \n{t}\n")
print (f"n: \n{n}\n")

t: 
tensor([3., 3., 3., 3., 3.])

n: 
[3. 3. 3. 3. 3.]



### This also works the othr way around:

In [16]:
n = np.ones(3)
print (f"n: \n{n}\n")

t = torch.from_numpy(n)
print (f"t: \n{t}\n")

np.add(n, 1, out=n)
print (f"n: \n{n}\n")
print (f"t: \n{t}\n")

n: 
[1. 1. 1.]

t: 
tensor([1., 1., 1.], dtype=torch.float64)

n: 
[2. 2. 2.]

t: 
tensor([2., 2., 2.], dtype=torch.float64)

